name: Deploy to GitHub Pages

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm i

    - name: Build
      run: npm run build
  
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout deployment branch
      uses: actions/checkout@v2
      with:
        ref: gh-pages

    - name: Copy build files
      run: cp -r build/* .

    - name: Commit changes
      uses: EndBug/add-and-commit@v7
      with:
        message: "Deploy build"
        add: .
        branch: gh-pages

    - name: Push changes
      uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: build
          token: ${{ secrets.ACTION_TOKEN }}
